export default Images = {
  logoWhite: require('../assets/logo.png'),
  logoGreen: require('../assets/logo1.png'),
  facebook: require('../assets/facebookIcon.png'),
  google: require('../assets/googleIcon.png'),
  avatar: require('../assets/avatar.webp'),
  // avatar: {
  //   uri: 'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png',
  // },
  _avatar:
    'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png',
  trailer1: require('../assets/trailer1.png'),
  trailer2: require('../assets/trailer2.png'),
  trailer3: require('../assets/trailer3.png'),
  thank: require('../assets/thank.png'),
  folder: require('../assets/folder.png'),
  faq: require('../assets/faq.png'),
  trcuk: require('../assets/truck.png'),
  trcuk2: require('../assets/truck2.png'),
  trcukVideo: require('../assets/TruckVideo.png'),
  Neighbour: require('../assets/Neighbour.png'),
  truck: require('../assets/truck.png'),
  truck1: require('../assets/truck1.png'),
  otp: require('../assets/VerifyOTPImage.png'),
  apple: require('../assets/apple.png'),
  play: require('../assets/play.png'),
  pdf: require('../assets/PDF.webp'),
  kg: require('../assets/kg.png'),
  package: require('../assets/package.png'),
  trailer: require('../assets/trailer.png'),
  calendar: require('../assets/calendar.png'),
  policy: require('../assets/policyIcon.png'),
  terms: require('../assets/termsIcon.png'),
};
